### PR TITLE
Use submodules for split-out repositories

### LINKED ISSUE #3: incorporate changes from other versions of the repo?
There is at least one other repo for this set of externals. It might be good to check if there are any fixes in these and incorporate them here.

Other repos found:

* <https://github.com/avilleret/mrpeach>

What do you think @avilleret?

### PR DESCRIPTION
**Pull request by umlaeute**
In order to prevent people (like me) to work on the wrong code base (because they happen to have checked out an uptodate version of `mrpeach`, but not e.g. of the separate `osc` repository), i propose to use `git submodules` to track the factored out sub-libraries (osc, midifile, binfile, slip)

- Closes: https://github.com/pd-externals/mrpeach/issues/3

### CODE REVIEW

**Comment by danomatika** [comment]
If the intent is to keep this repo as the traditional collection, then yes this would be a good idea.

**Comment by umlaeute** [comment]
well, what is the purpose of this repository, otherwise?

**Comment by danomatika** [comment]
I'll translate what I originally wrote: "Sounds good."

**Comment by reduzent** [comment]
@umlaeute  Thank you . I wasn't actually sure how to go about this after reading your expression of distaste  for submodules. Anyway, I think that is the best way forward.

**Pull request merged**
